### PR TITLE
update dependency, fix compat

### PR DESCRIPTION
**Pull request by babaq**
this works on julia v1.5

### CODE REVIEW

**Comment by babaq** [comment]
@marcpabst do you have time to look into this? right now, the master only have these compat issues to work on Julia v1.5.

**Comment by babaq** [comment]
@marcpabst it's been awhile, could you take a moment to at least fix the compat issues?

**Comment by marcpabst** [comment]
I'm really sorry for not responding, but this package was created years ago, and I'm sure (and hope) that there are many better ways to do ANOVAs in Julia by now.

**Comment by babaq** [comment]
Last time i checked, this is still a very important package for ANOVA.

**Comment by marcpabst** [comment]
You mean people actually use this? I created this package when the Julia ecosystem looked very different than it does today and my experience with the language was quite limited. If there is really interest, one could think about a re-write that makes use of the new language features while improving interoperability with other packages. 

But surely, someone must have created a better ANOVA package by now?

**Comment by babaq** [comment]
There is a summary thread [here](https://discourse.julialang.org/t/anova-tests-in-julia/1421/60). Looking at all the options, This one seems at a unique position by using GLM. Also, it would be really useful to including tests, especially compared to R, so users know what they can expect from the result.

I've been fixing compatibility issues on my [fork](https://github.com/babaq/ANOVA.jl), which i could create a pull request, but for most of codebase, you would know best how to modify to keep up with all the goodies of latest Julia.

**Pull request merged**
